FROM python:3.10

# Set the working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y libgl1

# Copy requirements first to leverage Docker cache
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy only the essential files
COPY camera_handler_new.py .
COPY employee_ui.py .
COPY face_recognition_handler.py .
COPY requirements.txt .

# Command to run the application
CMD ["streamlit", "run", "employee_ui.py", "--server.address=0.0.0.0"]
